---
title: Capstone Proposal
author: Heather Rugnetta
date: '2021-06-02'
slug: capstone-proposal
categories:
  - R
tags:
  - R Markdown
---

---
title: "Project Proposal: Helping Non-Profits Weather Uncertainity"
author: "Heather Rugnetta"
output:
 html_document:
    df_print: paged
    fig_height: 5
    fig_width: 8.5
    highlight: default
    number_sections: yes
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    table: kable
    self_contained: true

 
---

# Overview

COVID took a devastating toll on the economy.  Businesses shut their doors, employees were laid off, bills went unpaid.  Families and individuals struggled to make ends meet and reached out to community organizations like food pantries and utility assistance programs for help.  How did these organizations handle the influx of need? How did that impact the families and individuals who were being helped prior COVID?

This project will look at the demographics of individuals and families benefiting from non-profits, as well as the donors and volunteers that help those organizations exist.  Specifically, data from the Clackamas Service Center (CSC), an unhoused assistance program, before and during COVID-19 will be examined.  With this information, the Clackamas Service Center and similarly focused organizations can forge a path forward to better serve their clients if and when the next disaster strikes.


# Context 

Like many non-profits, Clackamas Service Center arouse from need.  Located in southeast Portland, the Clackamas Service Center is the area's few social service centers, providing low-income and homeless services to community members of the Clackamas and Multnomah counties.  It was one of the areas only shelters.  

The Clackamas Service Center relies heavily on in-kind donations (food, sanitation items, clothing) as well as volunteers to complete it's mission.  Pre-pandemic, the center was a location for the homeless to grab a meal 6 days a week, receive mail, and receive medical attention.  They could also get a shower, clothing, and shop the free market for groceries. When the pandemic hit, that changed.  Volunteers, who are primarily seniors, could no longer serve the center preparing meals without putting themselves at risk.  Donors, many of them local businesses, cut back or eliminated their donations straining the Clackamas Service Center further. And the need for food, both from the hot meal programs and the free market, increased dramatically as the pandemic rolled on. 

The Clackamas Service Center soldiered on, but how? What can the Clackamas Service Center learn from this crisis and, as a non-profit, can they prepare for the next disaster?


# Proposal

As a non-profit, the Clackamas Service Center does an excellent job of tracking their monetary donations and who their donors are. They know basic information about the donors, how often they give, and how much.  They know how much monetary value is distributed through to their staff and the items purchased to support their programs directly. They also track in-kind donations and volunteer hours.  

What they don't have a clear picture of is how they assist the community, or rather, a dollar amount per person per day.  They track the number of meals served, hygiene kits distributed, showers facilitated, and how many individuals they assist each day. Separately, they track demographics for those unhoused individuals who volunteer their information.  They also track the number of food boxes as well as those who receive them.   

The Clackamas Service Center is suffering from a wealth of information they cannot easily use. Housed in 4 different databases and excel sheets with no integration, they struggle to tell a concrete story of numbers.  They can illustrate a snapshot of numbers for a given quarter, but they have developed the information to tell a story over time.   

With the information the Clackamas Service Center shares with me, I hope to supplement their grant writing efforts to tell a better story, beyond anecdotes and snapshot numbers.  I want to help Clackamas Service Center consolidate their data, remove inherent duplications, and streamline their data collection while still maintaining the trust level they've established with their homeless clients. I also hope to illustrate the need vs supply (monetary, meals, services) over time.

# Conclusion 

Non-profits across the country were forced to pivot in 2020 when their sources of financial support fell short.  Many organizations that serve the homeless and food-insecure found themselves doubly hit when the need for their services increased as individuals lost their jobs.  Illustrating how money and services flow in non-profits, through donations and distribution, will help organizations like the Clackamas Service Center prepare for local and national crises.

The are some limitations to be assumed with the data, as it is all manually entered; one can assume that the volunteers who would have collected the data were also impacted by COVID. Sensitive information will likely be redacted and fidelity may be lost.  In-kind donations of meals and clothing are valued subjectively, and the monetary value to the organization will likely be inconsistent.


# An Aside

The organization is also seeking some assistance writing a job description for a future data science role, as well as some assistance creating a new, single interface for inputting data, versus the 4 they use now.
  